In [0]:
lst = [1, 2, 3]
lst.append(4)
print(lst)  # [1, 2, 3, 4]

lst.extend([5, 6])
print(lst)  # [1, 2, 3, 4, 5, 6]

lst.insert(2, 99)
print(lst)  # [1, 2, 99, 3, 4, 5, 6]

lst.remove(99)
print(lst)  # [1, 2, 3, 4, 5, 6]

print(lst.pop())  # Removes and returns last element -> 6
print(lst)  # [1, 2, 3, 4, 5]

lst.clear()
print(lst)  # []

lst = [1, 2, 3, 1, 2, 1]
print(lst.count(1))  # 3

lst = [10, 5, 8, 3]
lst.sort()
print(lst)  # [3, 5, 8, 10]

lst.reverse()
print(lst)  # [10, 8, 5, 3]

lst.index(3)






dct = {'a': 1, 'b': 2, 'c': 3}
print(dct.get('b'))  # 2
print(dct.get('x', 'Not Found'))  # Not Found

print(dct.keys())   # dict_keys(['a', 'b', 'c'])
print(dct.values()) # dict_values([1, 2, 3])
print(dct.items())  # dict_items([('a', 1), ('b', 2), ('c', 3)])

print(dct.pop('b'))  # Removes and returns value -> 2
print(dct)  # {'a': 1, 'c': 3}

print(dct.popitem())  # Removes last item -> ('c', 3)

dct.update({'d': 4})
print(dct)  # {'a': 1, 'd': 4}

dct.setdefault('e', 5)
print(dct)  # {'a': 1, 'd': 4, 'e': 5}

dct.clear()
print(dct)  # {}


# Dictionary Comprehension
squared_dict = {x: x**2 for x in range(5)}
print(squared_dict)  # {0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

dct = {'a': 10, 'b': 20, 'c': 5}
filtered_dict = {k: v for k, v in dct.items() if v > 10}
print(filtered_dict)  # {'b': 20}






nums = [3, 1, 4, 1, 5, 9]
print(sorted(nums))  # [1, 1, 3, 4, 5, 9]
print(sum(nums))  # 23
print(min(nums))  # 1
print(max(nums))  # 9

letters = ['a', 'b', 'c']
numbers = [1, 2, 3]
print(list(zip(letters, numbers)))  # [('a', 1), ('b', 2), ('c', 3)]
dict(zip(letters,numbers)) # {'a': 1, 'b': 2, 'c': 3}

print(list(enumerate(letters)))  # [(0, 'a'), (1, 'b'), (2, 'c')]
dict(enumerate(letters)) # {0: 'a', 1: 'b', 2: 'c', 3: 'd'} 

print(any([0, 0, 1]))  # True
print(all([1, 2, 3]))  # True

print(list(map(lambda x: x**2, nums)))  # [9, 1, 16, 1, 25, 81]

print(list(filter(lambda x: x > 3, nums)))  # [4, 5, 9]

  File <command-2370064707018056>:85
    dict(enumerate(letters)) {0: 'a', 1: 'b', 2: 'c', 3: 'd'}
                             ^
SyntaxError: invalid syntax

In [0]:
# students = [
#     {"name": "Alice", "score": 85,"class": 1},
#     {"name": "Bob", "score": 92,"class": 2},
#     {"name": "Charlie", "score": 78,"class": 3}
# ]
# # sorted(students, key = lambda x : x['score'], reverse=True)

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
list(filter(lambda x: x % 2 == 0, numbers)) 
# list(map(lambda x : x%2==0, numbers))

Out[2]: [2, 4, 6, 8]

True

'flo'

In [0]:
################################################################################################################################################
#              List                ##              List                ##              List                ##              List                #
################################################################################################################################################


# 1. Reverse a List
def reverse_list(nums):
    return nums[::-1]

nums = [3, 1, 4, 1, 5, 9]
print(reverse_list(nums))  # Output: [9, 5, 1, 4, 1, 3]

# 2. Find the Largest and Smallest Elements in a List
def find_largest_and_smallest(nums):
    return max(nums), min(nums)

nums = [3, 1, 4, 1, 5, 9]
print(find_largest_and_smallest(nums))  # Output: (9, 1)

# 3. Remove Duplicates from a List
def remove_duplicates(nums):
    return list(set(nums))

nums = [1, 2, 3, 2, 4, 4, 5]
print(remove_duplicates(nums))  # Output: [1, 2, 3, 4, 5]

# 4. Find the Intersection of Two Lists
def intersection(list1, list2):
    return list(set(list1) & set(list2))

list1 = [1, 2, 3, 4]
list2 = [3, 4, 5, 6]
print(intersection(list1, list2))  # Output: [3, 4]

# 5. Sum of All Numbers in a List
def sum_list(nums):
    return sum(nums)

nums = [3, 1, 4, 1, 5, 9]
print(sum_list(nums))  # Output: 23

# 6. Find the Index of the First Occurrence of an Element
def find_index(nums, target):
    return nums.index(target) if target in nums else -1

nums = [3, 1, 4, 1, 5, 9]
print(find_index(nums, 4))  # Output: 2

# 7. Flatten a Nested List
def flatten_list(nested_list):
    return [item for sublist in nested_list for item in sublist]

nested_list = [[1, 2], [3, 4], [5, 6]]
print(flatten_list(nested_list))  # Output: [1, 2, 3, 4, 5, 6]

# 8. Find the Most Frequent Element in a List
from collections import Counter
def most_frequent(nums):
    counter = Counter(nums)
    return counter.most_common(1)[0][0]

nums = [3, 1, 4, 1, 5, 9, 1]
print(most_frequent(nums))  # Output: 1

# 9. Find All Pairs in a List that Sum to a Target Value

def find_pairs(nums, target):
    pairs = []
    
    for i in range(len(nums)):
        for j in range(i+1, len(nums)):
            if nums[i] + nums[j] == target:
                pairs.append((nums[i], nums[j]))
                
    return pairs



def find_pairs(nums, target):  #(nums = [3, 1, 4, 1, 5, 9],8)
    pairs = []
    seen = set()
    for num in nums:
        complement = target - num
        if complement in seen:
            pairs.append((complement, num))
        seen.add(num)
    return pairs

nums = [3, 1, 4, 1, 5, 9]
print(find_pairs(nums, 6))  # Output: [(5, 1), (4, 2)]

# 10. Rotate a List by N Places
def rotate_list(nums, n):
    return nums[-n:] + nums[:-n]

nums = [1, 2, 3, 4]
print(rotate_list(nums, 2))  # Output: [3, 4, 1, 2]





################################################################################################################################################
#              Dictionary          ##              Dictionary          ##              Dictionary          ##              Dictionary          #
################################################################################################################################################

# 1. Merge Two Dictionaries
def merge_dicts(dict1, dict2):
    dict1.update(dict2)
    return dict1

dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
print(merge_dicts(dict1, dict2))  # Output: {'a': 1, 'b': 2, 'c': 3, 'd': 4}

# 2. Find the Key with the Maximum Value
def max_key_value(d):
    return max(d, key=d.get)

d = {'a': 1, 'b': 3, 'c': 2}
print(max_key_value(d))  # Output: b

# 3. Count the Frequency of Each Character in a String
def count_char_frequency(s):
    return {char: s.count(char) for char in set(s)}

s = "hello"
print(count_char_frequency(s))  # Output: {'h': 1, 'e': 1, 'l': 2, 'o': 1}

# 4. Invert a Dictionary
def invert_dict(d):
    return {v: k for k, v in d.items()}

d = {'a': 1, 'b': 2, 'c': 3}
print(invert_dict(d))  # Output: {1: 'a', 2: 'b', 3: 'c'}

# 5. Check if Two Dictionaries Are Equal
def are_dicts_equal(dict1, dict2):
    return dict1 == dict2

dict1 = {'a': 1, 'b': 2}
dict2 = {'a': 1, 'b': 2}
print(are_dicts_equal(dict1, dict2))  # Output: True

# 6. Get the Keys with a Specific Value
def get_keys_with_value(d, target_value):
    return [k for k, v in d.items() if v == target_value]

d = {'a': 1, 'b': 2, 'c': 1}
print(get_keys_with_value(d, 1))  # Output: ['a', 'c']


data = {'a': 10, 'b': 20, 'c': 10, 'd': 30}
target = 10

# filter returns an iterator; we convert it to a list
keys = list(filter(lambda k: data[k] == target, data))

print(keys)
# Output: ['a', 'c']

# 7. Remove a Key-Value Pair from a Dictionary
def remove_key(d, key):
    if key in d:
        del d[key]
    return d

d = {'a': 1, 'b': 2, 'c': 3}
print(remove_key(d, 'b'))  # Output: {'a': 1, 'c': 3}

# 8. Find the Common Keys Between Two Dictionaries
def common_keys(dict1, dict2):
    return list(dict1.keys() & dict2.keys())

dict1 = {'a': 1, 'b': 2}
dict2 = {'b': 3, 'c': 4}
print(common_keys(dict1, dict2))  # Output: ['b']

# 9. Merge a List of Dictionaries
def merge_dict_list(dict_list):
    result = {}
    for d in dict_list:
        result.update(d)
    return result

dict_list = [{'a': 1}, {'b': 2}, {'c': 3}]
print(merge_dict_list(dict_list))  # Output: {'a': 1, 'b': 2, 'c': 3}

# 10. Sort a Dictionary by Values
def sort_dict_by_value(d):
    return dict(sorted(d.items(), key=lambda item: item[1]))

d = {'a': 1, 'b': 3, 'c': 2}
print(sort_dict_by_value(d))  # Output: {'a': 1, 'c': 2, 'b': 3}

# 11.Combine dictionary keys using union and intersection.
from collections import Counter

data = ['apple', 'banana', 'apple', 'orange', 'banana', 'apple']
counts = Counter(data)

print(counts)
# Output: Counter({'apple': 3, 'banana': 2, 'orange': 1})

# Bonus: Get the most frequent item easily
print(counts.most_common(1)) 
# Output: [('apple', 3)]




################################################################################################################################################
#              string          ##              string          ##              string          ##              string                          #
################################################################################################################################################

# 1. Reverse Words in a Sentence
def reverse_words(s):
    return " ".join(s.split()[::-1])

print(reverse_words("Hello World Python"))  # Output: "Python World Hello"


# 2. Check if a String is a Permutation of Another
from collections import Counter

def is_permutation(s1, s2):
    return Counter(s1) == Counter(s2)

print(is_permutation("listen", "silent"))  # Output: True

# Generate Permutations in Python

from itertools import permutations

s = "abc"

result = permutations(s)

print(list(result))

["".join(p) for p in permutations(s)]




# 3. Find the First Non-Repeating Character
def first_unique_char(s):
    char_count = Counter(s)
    for char in s:
        if char_count[char] == 1:
            return char
    return None

print(first_unique_char("swiss"))  # Output: 'w'


# 4. Longest Common Prefix
def longest_common_prefix(words):
    if not words: return ""
    prefix = words[0]
    for word in words[1:]:
        while not word.startswith(prefix):
            prefix = prefix[:-1]
            if not prefix:
                return ""
    return prefix

print(longest_common_prefix(["flower", "flow", "flight"]))  # Output: "fl"


# 5. Count Occurrences of Each Character
def char_count(s):
    return dict(Counter(s))

print(char_count("hello"))  # Output: {'h': 1, 'e': 1, 'l': 2, 'o': 1}


# 6. Check if Two Strings are One Edit Away
def one_edit_away(s1, s2):
    if abs(len(s1) - len(s2)) > 1:
        return False
    from itertools import zip_longest
    diffs = sum(c1 != c2 for c1, c2 in zip_longest(s1, s2, fillvalue=""))
    return diffs <= 1

print(one_edit_away("pale", "ple"))  # Output: True


# 7. Compress a String (Run-Length Encoding)
def run_length_encoding(s):
    if not s: return ""
    encoded, count = [], 1
    for i in range(1, len(s)):
        if s[i] == s[i - 1]:
            count += 1
        else:
            encoded.append(s[i - 1] + str(count))
            count = 1
    encoded.append(s[-1] + str(count))
    return "".join(encoded)

print(run_length_encoding("aaabbc"))  # Output: "a3b2c1"


# 8. Find the Longest Palindromic Substring
def longest_palindrome(s):
    def expand_around_center(left, right):
        while left >= 0 and right < len(s) and s[left] == s[right]:
            left -= 1
            right += 1
        return s[left+1:right]
    
    result = ""
    for i in range(len(s)):
        for temp in (expand_around_center(i, i), expand_around_center(i, i+1)):
            if len(temp) > len(result):
                result = temp
    return result

print(longest_palindrome("babad"))  # Output: "bab" or "aba"


def all_palindromes(s):
    results = []
    for i in range(len(s)):
        for l, r in [(i, i), (i, i + 1)]:
            while l >= 0 and r < len(s) and s[l] == s[r]:
                results.append(s[l:r+1])
                l -= 1
                r += 1
    return results


# 9. Find the Most Frequent Word in a String
def most_frequent_word(s):
    words = s.split()
    return max(Counter(words), key=Counter(words).get)

print( most_frequent_word("apple banana apple orange banana apple") )  # Output: "apple"


# 10. Check if a String Follows a Given Pattern
def word_pattern(pattern, s):
    words = s.split()
    if len(pattern) != len(words):
        return False
    mapping, used_words = {}, set()
    for p, w in zip(pattern, words):
        if p in mapping:
            if mapping[p] != w:
                return False
        elif w in used_words:
            return False
        else:
            mapping[p] = w
            used_words.add(w)
    return True

print(word_pattern("abba", "dog cat cat dog"))  # Output: True

[9, 5, 1, 4, 1, 3]
(9, 1)
[1, 2, 3, 4, 5]
[3, 4]
23
2
[1, 2, 3, 4, 5, 6]
1
[(1, 5)]
[3, 4, 1, 2]
{'a': 1, 'b': 2, 'c': 3, 'd': 4}
b
{'l': 2, 'e': 1, 'h': 1, 'o': 1}
{1: 'a', 2: 'b', 3: 'c'}
True
['a', 'c']
{'a': 1, 'c': 3}
['b']
{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'c': 2, 'b': 3}

In [0]:
p = "abba"
d = {'a': 'dog', 'b': 'cat'}
" ".join(lambda x: d[x])

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File <command-6585326947860351>, line 3
      1 p = "abba"
      2 d = {'a': 'dog', 'b': 'cat'}
----> 3 " ".join(lambda x: d[x])

TypeError: can only join an iterable

In [0]:
pat = ['a', 'b', 'b', 'a']
mapp = {'a': 'dog', 'b': 'cat'}
" ".join(mapp.get(p) for p in pat )

'dog cat cat dog'

In [0]:
# Given a pattern string and a sentence, check if the sentence follows the same pattern.

p = "abba"
s = "dog cat cat dog"


def func(p,s):
    pat = [char for char in p]
    string = [word for word in s.split()]

    if len(p)!=len(s.split()):
        return False
    mapp = dict(zip(pat,string))
    if  " ".join(mapp.get(p) for p in pat ) == s:
        return True
    else:False

func(p,s)

False

In [0]:
# Given a pattern string and a sentence, determine if the sentence follows the same pattern.

s1, s2 = "abba", "dog cat cat dog"

def func(s1,s2):
    d = {}
    if len(list(s1)) != len(s2.split(' ') ):
        return False
    for i in range(len(s1)):
        d[s1[i]] = s2.split(' ')[i]
    print(d)
    if " ".join(["".join(d[s1[i]]) for i in range(len(s1))]) == s2:
        return True
    else:
        return False
func( s1,s2 )

{'a': 'dog', 'b': 'cat'}
Out[12]: True

In [0]:
#Count frequency of each character in a string
#  s = "Hello World Python"

# {l:s.count(l) for l in set(s) }

# " ".join(s.split()[::-1])

# from collections import Counter
# char_count = Counter(s)
# char_count



#Longest Common Prefix

#  lst = ["flower", "flow", "flight"]
# for i in range(len(lst[0]),0,-1):
#     if all( word.startswith(lst[0][0:i]) for word in lst[1:] ):
#         print(lst[0][0:i])
#         break




# from itertools import groupby
# st = 'aaabbc'
# "".join(char+str(len(list(group))) for char, group in groupby(st) )



# st = 'aaabbbc'

# output = ''

# count = 1

# for i in range(1, len(st)):
#     if st[i] == st[i-1]:
#         count += 1
#         print(count)
#     else:
#         output += st[i-1]+str(count)
#         print(output)
#         count = 1
# output += st[-1]+str(count)
# output

fl

In [0]:
# def merge_sort(arr):
#     if len(arr) <= 1:
#         return arr
#     mid = len(arr) // 2
#     left = merge_sort(arr[:mid])
#     right = merge_sort(arr[mid:])
#     return merge(left, right)

# def merge(left, right):
#     sorted_arr = []
#     i = j = 0
#     while i < len(left) and j < len(right):
#         if left[i] < right[j]:
#             sorted_arr.append(left[i])
#             i += 1
#         else:
#             sorted_arr.append(right[j])
#             j += 1
#     sorted_arr.extend(left[i:])
#     sorted_arr.extend(right[j:])
#     return sorted_arr

# print(merge_sort([5, 3, 8, 1, 2]))

In [0]:
''.is

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File <command-7059829933156795>, line 1
----> 1 "1231".isalapha()

AttributeError: 'str' object has no attribute 'isalapha'

In [0]:
# s = "Hello is World Python Python is is"


# dct = {}

# for word in s.split(" "):
#     if word not in list(dct.keys()):
#         dct[word] = 1
#     else:
#         dct[word] += 1

# dct

#################################
#################################

# s = "aaabbbaacc"
# output = [new_s[0]]

# def func(s):
#     for i in range(1,len(s)):
#         if new_s[i-1] == new_s[i]:
#             output.append(new_s[i])
#         else:
#             output.append(',')
#             output.append(new_s[i])
#     return ''.join([ i[0]+str(len(i)) for i in ''.join(output).split(',')])

# func(s)



#################################
#################################

Find all palindromic substrings in a given string (length > 2)
# s = "nana"

# def func(s):
#     lst =[]
#     for i in range(len(s)):
#         for j in range(i, len(s)):
#             if s[i:j+1] == s[i:j+1][::-1] and len(s[i:j+1]) > 2:
#                 lst.append(s[i:j+1]) 
#     return lst
            

# func(s)

#################################
#################################

Given a string and a number n, print all palindromic substrings of length n
# s = "naansppsbaab"
# def func(s,n):

#     for i in range(len(s)):
#         if s[i:i+n] == s[i:i+n][::-1] and len(s[i:i+n]) >n-1:
#             print(s[i:i+n])
#     return
# func(s,4)


#################################
#################################

Check if a given string is a palindrome, ignoring spaces, punctuation, and case sensitivity.

# s = "A man, a plan, a canal, Panama!a"

# def func(s):
#     string =  s.replace(',', '').replace(' ', '').replace('!', '').lower()
#     if string == string[::-1]:
#         print(" Planlindrome string" )
#     else:
#         print(" Not Plamlindrome string" )
# func(s)

Given a string, determine if it is a palindrome considering only alphanumeric characters and ignoring case.

# s = "A man, a plan, a canal, Panama!a"

# def func(s):
#     string = ''.join(c.lower() for c in s if c.isalnum())  # cleaner way
#     if string == string[::-1]:
#         print("Palindrome string")
#     else:
#         print("Not Palindrome string")

# func(s)


#################################
#################################

Print all palindromic substrings of a given string (length > 1).

# s = 'ababaaaa'

# def func(s):
#     for i in range(len(s)):
#         for j in range(i,len(s)):
#             string = s[i:j+1]
#             if string == string[::-1] and len(s[i:j+1])>1:
#                 print(s[i:j+1])

# func(s)

#################################
#################################

# s = 'ababaaaa'


# def func(s):
#     word = ''
#     length = 0
#     for i in range(len(s)):
#         for j in range(i, len(s)):
#             if s[i:j+1] == s[i:j+1][::-1] and len(s[i:j+1])>length:
#                 length += len(s[i:j+1])
#                 word = s[i:j+1] 
#     return word
# func(s)


#################################
#################################

# s = "xxxxxxxxxbbbbbaaavvvv"
# def func(s):
#     dct = {}
#     for i in s:
#         if i not in dct.keys():
#             dct[i] = 1
#         else:
#             dct[i] += 1


#     return dct
# dct = func(s)
# dct

# Sort a dictionary
# dict( sorted( dct.items(), key = lambda x:x[1], reverse =True ) )


#################################
#################################

s = "xxxbbaav"

def func(s):
    for i in range(len(s)):

        print(i)

    return

func(s)

0
1
2
3
4
5
6
7

In [0]:
s = "xxxxxxxxxbbbbbaaavvvv"

def func(s):
    dct = {}
    for c in set([c for c in s]):
        dct[c] = s.count(c)
    return dct.items()

func(s)

dict_items([('a', 3), ('x', 9), ('v', 4), ('b', 5)])

  File <command-2386666076326817>:1
    Hi Taha,
       ^
SyntaxError: invalid syntax

In [0]:
# Anagram\\


s1  = "Divy"
s2  = "yivd"

# def func(s1,s2):
#     global d1, d2
#     d1,d2 = {},{}
    
#     if len(s1) == len(s2):
#         for i in s1:
#             if i not in d1.keys():
#                 d1[i] = d1.get(i, 0) + 1

#         print(d1)
#         for i in s2:
#             if i not in d2.keys():
#                 d2[i] = d2.get(i, 0) + 1
#         print(d2)
#         if d1 == d2:
#             return print("Anagram")
#     else:
#         return print('NOT an Anagram')


# func(s1,s2)

# from collections import Counter
# def func(s1,s2):
#     if len(s1)!=len(s2):
#         return print("Not Anagram")
#     d1,d2 = Counter(s1), Counter(s2)
#     if d1==d2:
#         return print("ANAGRAM"),print(d1),print(d2)
#     else:
#         print("Not Anagram")
    
# func(s1,s2)

Not Anagram

In [0]:
st = "baba"
st[::-1]

Out[19]: 'abab'

In [0]:
dict1 = { 'a': 5, 'b': 2, 'c': 4 }
dict2 = { 'b': 3, 'c': 4, 'd': 4 }
dict3 = { 'b': 3, 'c': 4, 'f': 4 }
# print( dict1.keys() | dict2.keys() )
# print( dict1.keys() & dict2.keys() )

merged_dict = {**dict1, **dict2, **dict3}
dict1.get('b',0)

# sorted(dict1, key = lambda x:x[1]  )
# dict(sorted(sum_dict.items(), key=lambda item: item[1])  )
# sorted(dict1.items(), key = lambda item:item[1]  )

Out[32]: 2

In [0]:
cols = ["A","B","C","D"]

data = [
        ("A0", "A1", "A2", "A3"),
        ("B0", "B1", "B2", "B3"),
        ("C0", "C1", "C2", "C3"),
        ("D0", "D1", "D2", "D3") 
       ]

spark.createDataFrame(data,cols).display()

A,B,C,D
A0,A1,A2,A3
B0,B1,B2,B3
C0,C1,C2,C3
D0,D1,D2,D3

In [0]:
import pandas as pd


df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)


df2 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C0", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[4, 5, 6, 7],
)


df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },
    index=[8, 9, 10, 11],
)

df = pd.concat([df1,df2,df3])
df_join = pd.merge(df1,df2, on = 'A' )
df_join.head(20)

,A,B_x,C_x,D_x,B_y,C_y,D_y
0,A0,B0,C0,D0,B4,C0,D4
1,A1,B1,C1,D1,B5,C5,D5

In [0]:
import pandas as pd

df = pd.DataFrame(
{
    'Name' : ['divyam', 'pal', 'kal', 'ansh'],
    "Age"  : [30, 33, 31, 25]
}
)
df_m = df.merge(df,how = 'left', left_on = ['Name'], right_on = ['Name'])
df_m.head()

,Name,Age_x,Age_y
0,divyam,30,30
1,pal,33,33
2,kal,31,31
3,ansh,25,25

In [0]:
lisst = [0,0,1,3,4,4]

# for i in lisst:
#     if i==0:
#         lisst.remove(i)
#         lisst.append(i)
# lisst


for i in lisst:
    if i == 0:
        lisst.remove(i)
lisst

Out[51]: [0, 1, 3, 4, 4]

In [0]:
a = [1,2,3]
b = [4,5,6]

# [(x,y) for x in a for y in b]

# res = []
# for x in a:
#     for y in b:
#         res.append((x,y))
# res

In [0]:
lisst = [0,0,1,3,4,4]

# dic = {}
# for i in set(lisst):
#     dic[i] = lisst.count(i)
    


# [ele for ele in lisst]
# [x for x in a for a in b]

a = [1,2,3]
b = [4,5,6]

[x+y for x in a for y in b]

# 5,6,7,6,7,8,7,8,9

In [0]:
string = 'a a b b fg h ta aa aa'

# string[::-1]
# string.count('b')
# string.find('b')
# lisst = string.split(" ")
# '%'.join(lisst)
# ''.join(lisst[::-1])

Out[16]: 'a%a%b%b%fg%h%ta%aa%aa'

In [0]:
string = 'a a b b fg h ta aa aa'
lisst = string.split(' ')
dic = {}
for str in set(lisst):
    dic[str] = lisst.count(str)

dic

Out[1]: {'b': 2, 'h': 1, 'a': 2, 'fg': 1, 'ta': 1, 'aa': 2}

In [0]:
# string = "DIVYAM"
# list(string)
# "".join(list(string)[::-1])



# string = "DIVYAM"
# string[::-1]
# l = list("".join(string[::-1]))
# print(l)
# l.reverse()
# print(l)

Out[4]: {'b': 2, 'a': 2, 'aa': 2, 'h': 1, 'fg': 1, 'ta': 1}

In [0]:

# dct = {'b': 2, 'h': 1, 'a': 2, 'fg': 1, 'ta': 1, 'aa': 2}

# # dict(sorted(dct.items(), key=lambda x:x[1], reverse=True))

# lst = list(dct.items())

# def func(lst):
#     if len(lst) <=1:
#         return lst
#     p = lst[len(lst)//2][1]
#     l = [x for x in lst if x[1] < p]
#     m = [x for x in lst if x[1] == p]
#     r = [x for x in lst if x[1] > p]
#     return func(r) + m + func(l)

# dict(func(lst))

Out[21]: {'b': 2, 'a': 2, 'aa': 2, 'h': 1, 'fg': 1, 'ta': 1}

In [0]:
for x in lst:
    print(x[1])

2
1
2
1
1
2

In [0]:
lisst = [1,1,2,23,3,54,5,5]

# lisst.pop(0) # poped the element present on the index 0
# lisst.remove(1) # removed the first occurance of the element.

# del lisst[0] # removes the element present on the 0th index

# lisst.index(3) # to get the index of any element presnent in the list

# lisst.reverse() # revere is used to reverse the string
# lisst.count(1) # count is used to count the element present in the list.

Out[22]: [1, 1, 2, 23, 3, 54, 5, 5]

In [0]:
import itertools

for i in itertools.count(1):
    print(i)
    break

1

In [0]:
lisst = [1,1,2,23,3,54,5]
# new_list = []

# for ele in lisst:
#     if ele not in new_list:
#         new_list.append(ele)

# new_list
list(set(lisst))

Out[60]: [1, 2, 3, 5, 54, 23]

In [0]:
from collections import OrderedDict
lisst = [1,1,2,23,3,54,5]
OrderedDict.fromkeys(lisst)

Out[55]: OrderedDict([(1, None),
             (2, None),
             (23, None),
             (3, None),
             (54, None),
             (5, None)])

In [0]:
lst = [1,1,2,23,3,54,5]

def is_sorted(lst):
    return all( lst[i] <= lst[i+1] for i in range(len(lst)-1) )

is_sorted(lst)

Out[37]: False

In [0]:
numbers = [2, 4, 6, 3, 10]
# result = all(num % 2 == 0 for num in numbers)
# result = any(num % 2 != 0 for num in numbers)
print(result)

True

In [0]:
lst = [1,1,2,23,3,54,5]

sorted(lst,reverse = True)

Out[62]: [54, 23, 5, 3, 2, 1, 1]

In [0]:
lst = [1,1,42,23,3,4,5]

# def second_largest(lst):
#     return sorted(set(lst), reverse= True)[1]
# second_largest(lst)

for i in range(len(lst)):
    ele = max(lst[i:])
    print(lst[i:],ele)
    lst.remove(ele)
    lst.insert(0,ele)

# lst.pop(-1)

Out[67]: 23

In [0]:
def longest_palindrome(s):
    start, end = 0, 0
    def expand_around_center(left, right):
        while left >= 0 and right < len(s) and s[left] == s[right]:
            left -= 1
            right += 1
        return left + 1, right - 1 

    for i in range(len(s)):
        l1, r1 = expand_around_center(i, i)    
        l2, r2 = expand_around_center(i, i + 1)
        if r1 - l1 > end - start:
            start, end = l1, r1
        if r2 - l2 > end - start:
            start, end = l2, r2

    return s[start:end + 1]


s = 'adadadada'
longest_palindrome(s)

Out[82]: 'adadadada'

In [0]:
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]
# common_elements  = list(set(list1) & set(list2))
# unique_elements  = list(set(list1) | set(list2))
# unique_elements

# set(list1) | set(list2)

set(list1) | set(list2)

Out[71]: {1, 2, 3, 4, 5, 6, 7}

In [0]:
step = 2
lst  = [1, 2, 10, 55, 3, 4, 5, 23, 45, 65]

def shift_list(lst,step):
    return lst[-step::] + lst[:-step]
shift_list(lst,step)


# lst = [1, 2, 10, 55, 3, 4, 5, 23, 45, 65]
# step = 1
# lst[step:] + lst[:step]

Out[46]: [45, 65, 1, 2, 10, 55, 3, 4, 5, 23]

In [0]:
dict1 = {'a': 1, 'b': 2}
dict2 = {'b': 3, 'c': 4}
merged_dict = {**dict1, **dict2}
dict1.update(dict2)
dict1

Out[30]: {'a': 1, 'b': 3, 'c': 4}

In [0]:
d = {'b': 5, 'c': 4, 'e': 1}

d = {k:v for k,v in sorted(d.items(), key = lambda item:item[1])}

d

Out[48]: {'e': 1, 'c': 4, 'b': 5}

In [0]:
d = {'b': 5, 'c': 5, 'e': 10, 'a':33, 'j':3}

# new_d = {}

# for k,v in sorted([ (v,k) for k,v in d.items() ]):
#     new_d[v] = k


# new_d

# also

# {k:v for k,v in sorted(d.items(), key = lambda a : a[1] ) }

In [0]:
d = {'b': 5, 'c': 4, 'e': 1}

d.pop('c')

d

Out[94]: {'b': 5, 'e': 1}

In [0]:
d = {'b': 5, 'c': 10, 'e': 1}

sorted( d.items(), key = lambda item:item[1] )[-1][0]

In [0]:
lst = [8, 7, 6, 5, 4, 3, 2, 1, 9]

def merge_sort(lst):
    if len(lst) <1:
        return lst
    mid = len(lst)//2
    left_part = lst[:mid]
    right_part = lst[mid:]

    left_part  = merge_sort(left_part)
    right_part = merge_sort(right_part)
    
    return merge(left_part,right_part)

merge_sort(lst)

---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
File <command-1768757165294367>:15
     11     right_part = merge_sort(right_part)
     13     return merge(left_part,right_part)
---> 15 merge_sort(lst)

File <command-1768757165294367>:10, in merge_sort(lst)
      7 left_part = lst[:mid]
      8 right_part = lst[mid:]
---> 10 left_part  = merge_sort(left_part)
     11 right_part = merge_sort(right_part)
     13 return merge(left_part,right_part)

File <command-1768757165294367>:10, in merge_sort(lst)
      7 left_part = lst[:mid]
      8 right_part = lst[mid:]
---> 10 left_part  = merge_sort(left_part)
     11 right_part = merge_sort(right_part)
     13 return merge(left_part,right_part)

    [... skipping similar frames: merge_sort at line 10 (1 times)]

File <command-1768757165294367>:11, in merge_sort(lst)
      8 right_part = lst[mid:]
     10 left_part  = merge_sort(left_part)
---> 11 right_part = merge_sort(right_part)
     13 return merge(left_part,right_part)

File <command-1768757165294367>:11, in merge_sort(lst)
      8 right_part = lst[mid:]
     10 left_part  = merge_sort(left_part)
---> 11 right_part = merge_sort(right_part)
     13 return merge(left_part,right_part)

    [... skipping similar frames: merge_sort at line 11 (2968 times)]

File <command-1768757165294367>:11, in merge_sort(lst)
      8 right_part = lst[mid:]
     10 left_part  = merge_sort(left_part)
---> 11 right_part = merge_sort(right_part)
     13 return merge(left_part,right_part)

File <command-1768757165294367>:10, in merge_sort(lst)
      7 left_part = lst[:mid]
      8 right_part = lst[mid:]
---> 10 left_part  = merge_sort(left_part)
     11 right_part = merge_sort(right_part)
     13 return merge(left_part,right_part)

File <command-1768757165294367>:4, in merge_sort(lst)
      3 def merge_sort(lst):
----> 4     if len(lst) <1:
      5         return lst
      6     mid = len(lst)//2

RecursionError: maximum recursion depth exceeded while calling a Python object

In [0]:
lst = [8, 7, 6, 5, 4, 3, 2, 1, 9]

lss= [9]

merge(lst,lss)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
File <command-493126478704641>:5
      1 lst = [8, 7, 6, 5, 4, 3, 2, 1, 9]
      3 lss= [9]
----> 5 merge(lst,lss)

NameError: name 'merge' is not defined

In [0]:
import copy
lst = [1,2,[3,4]]

lst1 = copy.copy(lst)
lst2 = copy.deepcopy(lst)

lst[2][0] = 10

print(lst1)
print(lst2)

[1, 2, [10, 4]]
[1, 2, [3, 4]]

In [0]:
pat = [1,2,3]
seq = [1,2,3,34,4,4,1,2,333,4444]

seq1 = ','.join(str(i) for i in seq )
seq2 = ','.join(str(i) for i in pat ) + ','
print(seq1)
print(seq2)
# seq2 in seq1

1,2,3,34,4,4,1,2,333,4444
1,2,3,

In [0]:
def list_contains(pat, seq): 
    n = len(pat) 
    return any(pat == seq[i:i + n] for i in range(len(seq)-n + 1))

pat = [1,2,3]
seq = [0,1,2,3,4,5,6,7,8,9]
list_contains(pat, seq)

Out[60]: True

In [0]:
my_list = [0,1,2,3,4,5,6,7,8,9]
pat     = [1,2,3]
any( my_list[i:i+len(pat)] == pat for i in range(len(my_list)- len(pat)+1) )

In [0]:
my_list = [5, 2, 9, 9, 1, 5, 6, 3]

def func(lst):

    tmp = lst[0]
    for ele in lst:
        
    return

func(my_list)

In [0]:
def min_fun(lst):
    minn = lst[0]
    for i in lst:
        if i < minn:
            minn = i
    return minn

lst_sorted = []
my_list    = [5, 2, 9, 9, 1, 5, 6, 3]

for i in range(len(my_list)):
    minimum = min_fun(my_list)
    lst_sorted.append(minimum)
    my_list.remove(minimum)

lst_sorted

Out[53]: [1, 2, 3, 5, 5, 6, 9, 9]

In [0]:
def quick_sort(unsorted_array):
    
    if len(unsorted_array)<= 1:
        return unsorted_array
    
    pivot = unsorted_array[-1]
    left = []
    right = []

    for i in unsorted_array[:-1]:
        if i < pivot:
            left.append(i)
        else:
            right.append(i)

    return quick_sort(left) + [pivot] + quick_sort(right)



unsorted_array = [7, 2, 1, 6, 8, 5, 3, 4,-1,0,-1]
quick_sort(unsorted_array)

# explaination

# unsorted_array = [7, 2, 1, 6, 8, 5, 3, 4,-1,0,-2, -1]

# pivot = -1
# left = [-2]
# right = [7, 2, 1, 6, 8, 5, 3, 4,-1,0]



# pivot = 0
# left = [-1]
# right = [7, 2, 1, 6, 8, 5, 3, 4]

# pivot = 4
# left = [1,2,3]
# right = [7, 6, 8, 5]
# [1,2,3]

# pivot = 3
# left = [1,2]
# right = []
# [1,2]

# pivot = 2
# left = [1]
# right = []
# [1] + [2] + [3] + [4] +

Out[54]: [-1, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8]

In [0]:
unsorted_array = [7, 2, 1, 6, 8, 5, 3, 4,-1,0,-1]

sorted( unsorted_array )

Out[55]: [-1, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8]

In [0]:

string = "elle"

def is_palandorme(string):
    return string == string[::-1]


if is_palandorme(string):
    print("Palendrome")
else:
    print("Not Palendrome")

Palendrome

In [0]:

lst1 = [1,2,3,4,5]
lst2 = [7,8,9,4,5]

[ele for ele in lst1 if ele in lst2]

# list(set(lst1) & set(lst2))

In [0]:

# Check for balanced parentheses.
# Input : {[]{()}}
# Output : Balanced

# Input : [{}{}(]
# Output : Unbalanced

string = '{[]{()}}'

def func(s):
    dic = { "{" : "}","[" : "]","(" : ")" }
    for i in string:

In [0]:
def pair_str(string):
    string_pair = set()
    for i in range(len(string)-1):
        pair = string[i:i+2]
        if len(pair) == 2 and pair[0] == pair[1]:
            string_pair.add(pair)
    return string_pair

sampleStr = "ffbbvv"
pair_str(sampleStr)


# sampleStr = "fffabbxcvvvvvucacbcdz"
# lst = []
# for i in range(len(sampleStr)-1):
#     if sampleStr[i] == sampleStr[i+1]:
#         lst.append(sampleStr[i:i+2])
#     # sampleStr[0]
# lst

Out[86]: {'bb', 'ff', 'vv'}

In [0]:
my_list = [5, 2, 9, 9, 1, 5, 6, 3,8]

def min_fun(my_list):
    minn = my_list[0]
    for i in my_list:
        if i < minn:
            minn = i
    return minn

min_fun(my_list)

sorted_list = []

def sort_list(my_list):
    for i in range(len(my_list)):
        minn = min_fun(my_list)
        sorted_list.append(minn)
        my_list.remove(minn)
    return None

sort_list(my_list)
sorted_list

Out[57]: [1, 2, 3, 5, 5, 6, 8, 9, 9]

In [0]:
my_list = [5, 2, 9, 9, 1, 5, 6, 3,8,100,-100]

def quick_sort(my_list):
    if len(my_list) <= 1:
        return my_list
    pivot = my_list[-1]
    left = []
    right = []
    for i in my_list[:-1]:
        if i <= pivot:
            left.append(i)
        if i > pivot:
            right.append(i)
    return quick_sort(left) + [pivot] + quick_sort(right)

quick_sort(my_list)

In [0]:
# class Student:
#     pass

# divyam = Student()
# saxena = Student()
# print(divyam)
# print(saxena)

# ######################################################################

# divyam.age = "24 Years"
# divyam.org = "Amazon"

# saxena.age = "28 Years"
# saxena.org = "Google"

# print(divyam.age)
# print(divyam.org)

# print(saxena.age)
# print(saxena.org)

######################################################################

# class Student:              #this is class
#     numb_of_leaves = 15
#     pass

# divyam = Student()              # this is an instance variable
# saxena = Student()
# divyam.age = "24 Years"
# saxena.age = "28 Years"

# print(divyam.numb_of_leaves)
# print(saxena.numb_of_leaves)
# print(Student.numb_of_leaves)

# print(divyam.__dict__)

######################################################################

# class Student:              #this is class
#     numb_of_leaves = 15
    
#     def print_details(self):        #this is a method
#         return self.age

# divyam = Student()
# divyam.age = "25"
# divyam.print_details()

######################################################################

# class Student:
#     def __init__(self,aname,aage,aorg):            # this is a constructor, whatever argument is passed to the class will be handled by this constructor.
#         self.name = aname                          # here aname is the argument and self.name is the instance
#         self.age = aage
#         self.org = aorg

#     def print_details(self):                       #this is a method
#         return f"The name is {self.name} and age is {self.age} and org is {self.org}"




# divyam = Student('divyam','24','Amazon')
# divyam.print_details()
# saxena = Student('saxena','36','LinkedIn')
# saxena.print_details()


######################################################################

# class rectangle:
#     def __init__(self,length,breadth):
#         self.length = length
#         self.breadth = breadth

#     def print_area(self):
#         area = self.length * self.breadth
#         return area
    
#     def print_circumferance(self):
#         area = 2 * (self.length + self.breadth)
#         return area

# print(rectangle(5,6).print_area())
# print(rectangle(5,6).print_circumferance())

In [0]:
lst = [1, 2, 4, 5, 6, 0, 8]

em_lst = []
mn = min(lst)

for i in lst:
    mn = mn + 1
    if mn not in lst:
        em_lst.append(mn)

em_lst

In [0]:
# a = lambda x, y : x*y
# print(a(7, 19))

lb_fun = lambda x,y,z : x*y*z

lb_fun(1,2,3)

In [0]:
string = "DIVYAM"
string.swapcase()

Out[91]: 'divyam'

In [0]:
newList = [12, 35, 9, 56, 24]
newList[0], newList[-1] = newList[-1], newList[0]
newList

Out[58]: [24, 35, 9, 56, 12]

In [0]:
test_list = ['Gfg', 'is', 'best', 'for', 'Geeks']

[ele.replace('G','-').replace('e','G').replace('-','e') for ele in test_list]

Out[66]: ['efg', 'is', 'bGst', 'for', 'eGGks']

In [0]:
def compare(x,y):
    if x>y:
        return print("the bigger number is : "+ str(x))
    elif x==y:
        return print("both the numbers are equal")
    else:
        return print("the bigger number is : "+ str(y))



compare(10,10)

In [0]:

lst = [10, 11, 12, 13, 14, 15] 
new_lst = []
for i in lst:
    new_lst.insert(0,i) 
new_lst


# lst[::-1]

In [0]:
lst = [10, 1117, 22, 23, 14, 15]
new = []
for i in lst:
    n = 0
    for j in str(i):
        n = n + int(j)
    new.append(n)

new

In [0]:
lst = [10, 1117, 22, 23, 14, 15]

def element_sum(lst):
    new = []

    for i in lst:
        if len(str(i))>1:
            n = 0
            for j in str(i):
                n = n+ int(j)
            new.append(n)
        else:
            continue
    return element_sum(new)

element_sum(lst)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File <command-3723143827684444>:16
     13             continue
     14     return element_sum(new)
---> 16 element_sum(lst)

File <command-3723143827684444>:7, in element_sum(lst)
      4 new = []
      6 for i in lst:
----> 7     if len(str(i))>1:
      8         n = 0
      9         for j in str(i):

TypeError: 'str' object is not callable

In [0]:
lst = [10,10, 1117, 22, 10000, 14, 15]

new = set(lst)
new.remove(max(new))
max(new) # This is a different way of doing this.

In [0]:
test_list = ["Gfg", 3, "is", 8, "Best", 10, "for", 18, "Geeks", 33]

new_dict = {}
n = len(test_list)
for ind in range(0,n,2):
    new_dict[test_list[ind]] = test_list[ind+1]

new_dict

In [0]:
# file_path='/dbfs/FileStore/tables/data.csv'
# # file_path = "/dbfs/path/to/your/example.txt"  # Replace with the actual path

# # Open the file using the open function
# with open(file_path, 'r') as file:
#     content = file.read()

# there is issues with the above code we can a file using sc onn databricks

# file_path='dbfs:/FileStore/tables/data.csv'
# # sc.textFile(file_path).collect()

# with open(file_path,'r') as file:
#     content = file.read()

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
File <command-2637543494624003>:5
      1 # file_path='/dbfs/FileStore/tables/data.csv'
      2 # # file_path = "/dbfs/path/to/your/example.txt"  # Replace with the actual path
      3
      4 # # Open the file using the open function
----> 5 # with open(file_path, 'r') as file:
      6 #     content = file.read()
      7
      8 # there is issues with the above code we can a file using sc onn databricks
     10 file_path='dbfs:/FileStore/tables/data.csv'
     11 # sc.textFile(file_path).collect()

FileNotFoundError: [Errno 2] No such file or directory: '/dbfs/FileStore/tables/data.csv'

In [0]:
test_list = [['a', 'b', 1, 2], ['c', 'd', 3, 4], ['e', 'f', 5, 6]]

res = dict()
for ls in test_list:
    res[tuple(ls[:2])] = tuple(ls[2:])
res
# another approch
# test_list = [['a', 'b', 1, 2], ['c', 'd', 3, 4], ['e', 'f', 5, 6]] 
# { tuple(ls[:2]) : tuple(ls[2:]) for ls in test_list }

Out[76]: {('a', 'b'): (1, 2), ('c', 'd'): (3, 4), ('e', 'f'): (5, 6)}

In [0]:
test_list = [['a', 'b', 1, 2], ['c', 'd', 3, 4], ['e', 'f', 5, 6]]

def func(ls):
    dct = {}
    for i in ls:
        dct[i[0]] = i[2]
        dct[i[1]] = i[3]
        
    return dct


func(test_list)

Out[77]: {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}

In [0]:
def quick(lst):
    if len(lst) <= 1:
        return lst
    pivot = lst[-1]
    left  = []
    right = []

    for i in lst[:-1]:
        if i < pivot:
            left.append(i)
        if i >= pivot:
            right.append(i)
    return quick(left) + [pivot] + quick(right)


lst = [10,10, 1117, 22, 10000, 14, 15,-1,0]
quick(lst)

In [0]:
lst1 = [1,2,3,4]
lst2 = [5,6,3,4]

# common elements b/w l1 and l2
# [ele for ele in lst1 if ele in lst2 ]
# non common elements b/w l1 and l2
[ele for ele in lst1 if ele not in lst2 ] + [ele for ele in lst2 if ele not in lst1 ]

Out[84]: [1, 2, 5, 6]

In [0]:
import random
lst = [10,34,34,34]
random.choice(lst)

In [0]:
test_list = [[4, 1, 6], [7, 8], [4, 10, 8],3]
for ele in test_list:
    if type(ele)== list:
        ele.sort(reverse=False)
test_list

Out[82]: [[1, 4, 6], [7, 8], [4, 8, 10], 3]

In [0]:
n= 5
for i in range(0,n+1):
    print(' ' * (n-i) +'*'*i)

In [0]:
arr = [1, 1, 1, 64, 23, 64, 22, 22, 22]

for i in range(len(arr)-2):
    s = set([arr[i], arr[i+1], arr[i+2]])
    if len(s)==1:
        print(arr[i])

1
22

In [0]:
arr1 = [1,2,2,3,4,5,100,100,1]

def compare(x,y):
    if x>=y:
        return x
    else: 
        return y

new = []
for ele in range(len(arr1)-1):
    result = compare(arr1[ele],arr1[ele+1])
    new.append(result)

new

Out[80]: [2, 2, 3, 4, 5, 100, 100, 100]

In [0]:
from itertools import combinations, permutations

permutations(range(3),2)

In [0]:
arr1 = [1,2,2,3,4,5,100,100,1000]
item = 2
[i for i in arr1 if i!=item]

# [i for i in arr1 if arr1.count(i) < 2 ]

# lst = []
# arr1 = [1,2,2,3,4,5,100,100,1000]
# for i in arr1:
#     if i not in lst:
#         lst.append(i)
# lst 


# list(set(arr1))

In [0]:
test_list1 = ['Gfg', 'is', 'best']
test_list2 = [0, 1, 2, 1, 0, 0, 0, 2, 1, 1, 2, 0]

[test_list1[i] for i in test_list2]

Out[79]: ['Gfg',
 'is',
 'best',
 'is',
 'Gfg',
 'Gfg',
 'Gfg',
 'best',
 'is',
 'is',
 'best',
 'Gfg']

In [0]:
test_list = ["geeks", "for", "geeks", "is", "best"]

# test_list[::-1]
# [i[::-1] for i in test_list ]

In [0]:
test_list = ["Gfg is good for learning", "Gfg is for geeks", "I love G4G"]
k = 'g'
for i in test_list:
    for j in i.split(' '):
        if j.startswith(k):
            print(j)

good
geeks

In [0]:
test_list = ["Gfg is good for learning", "Gfg is for geeks", "I love G4G"]
new = []
for ele in test_list:
    sub = ele.split(' ')
    new.extend(sub)
new

Out[77]: ['Gfg',
 'is',
 'good',
 'for',
 'learning',
 'Gfg',
 'is',
 'for',
 'geeks',
 'I',
 'love',
 'G4G']

In [0]:
'div' in 'divyam'

Out[80]: True

In [0]:
test_list1 = ['GeeksforGeeks', 'is', 'Best', 'For', 'Geeks', 'And', 'Computer Science']
test_list2 = [['Geeks', 'Gks'], ['And', '&'], ['Computer', 'Comp']]

sub = dict(test_list2)
for k,v in sub.items():
    for i in test_list1:
        if k in i:
            test_list1[test_list1.index(i)] = i.replace(k,v)
test_list1

Out[81]: ['GksforGks', 'is', 'Best', 'For', 'Gks', '&', 'Comp Science']

In [0]:
# 'divy'.capitalize()

# 'divy'.casefold()

# 'divy'.find('v')

# 'divy'.index('d')

Out[76]: 'Divy'

In [0]:
numbers = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4,100]

keys = set(numbers)
new_dict = {}
for k in keys:
    new_dict[k] = numbers.count(k)
new_dict

Out[60]: {1: 1, 2: 2, 3: 3, 100: 1, 4: 4}

In [0]:
dict1 = {'a': 1, 'b': 2}
dict2 = {'b': 3, 'c': 4}

# dict1.update(dict2)
# dict1.values()
# dict1.keys()

In [0]:
dict1 = {'a': 1, 'b': 2}
dict2 = {'b': 3, 'c': 4}

{  k:v for d in [dict1, dict2]  for k,v in d.items()  }

# dict1.update(dict2)
# dict1

Out[62]: {'a': 1, 'b': 3, 'c': 4}

In [0]:
list1 = [1, 2, 2, 2, 3, 4, 5,6,6,6,6]
list2 = [2, 2, 3, 3, 4, 6,6,6,6]


# def function(l1,l2):
#     new_dict = {}

#     for item in list1:
#         if item in list2:
#             if item in new_dict:
#                 new_dict[item] += 1
#             else:
#                 new_dict[item] = 1

#     return new_dict

# function(list1,list2).  # Not correct solution






# Below is the correct solution.

list1 = [1, 2, 2, 2, 3, 4, 5,6,6,6,6,67]
list2 = [2, 2, 3, 3, 4, 6,6,6,6,100]

list1_d = { i:list1.count(i) for i in set(list1)}
list2_d = { i:list2.count(i) for i in set(list2)}



final = {}
for i in set(list1_d.keys()) | set(list2_d.keys()):
    if i in list1_d and i in list2_d:
        value = min(list1_d[i],list2_d[i])
        final.update({i:value})  
final

Out[63]: {2: 2, 3: 1, 4: 1, 6: 4}

In [0]:
list1 = [1, 2, 2, 2, 3, 4, 5,6,6,6,6,6,6,6,7]
list2 = [2, 2, 3, 3, 4, 6,6,6,6,7 ]

def function(list1,list2):
    s1 = set(list1)
    s2 = set(list2)
    new_dict = {}
    for i in set(s1 & s2):
        new_dict[i] = min(list1.count(i),list2.count(i))
    return new_dict

function(list1,list2)

Out[72]: {2: 2, 3: 1, 4: 1, 6: 4, 7: 1}

In [0]:
# a = {1: 1,
#      2: 3,
#      3: 1,
#      4: 1,
#      5: 1,
#      6: 4,
#      67:1
#     }
# a.update({67:2})
# # a.update({31:2})

string = 'bbaaccbbbaa'
string.find('a')

Out[71]: 2

In [0]:
string = 'aabbaaccbbbaa'

# string.find(a)

lst = [i for i in string]

for index in range(len(lst)):
    if lst[index] == lst[index+1]

In [0]:
string = 'aabbaaccbbbaaffff'

def func(string):
    curr_char = string[0]
    char_count = 0
    final_count = 0
    for char in string:
        if char == curr_char:
            char_count += 1
        else:
            if final_count < char_count:
                final_count = char_count
            
            curr_char = char
            char_count = 1
            
    if final_count < char_count:
        final_count = char_count
    return final_count


func(string)

Out[65]: 4

In [0]:
string = 'aabbbbaaccbbbaa'


current_char = ''
current_count = 0

max_char = ''
max_count = 0

for char in string:
    if char == current_char:
        current_count += 1
    else:
        current_char = char
        current_count = 1
        
    if current_count > max_count:
        max_count = current_count
        max_char = current_char

print(max_char)
print(max_count)

b
4

In [0]:
sentence = """
Have free hours and love children? Drive kids to school, soccer practice and other activities.
"""
lst = sentence.split(' ')
new_lst = []
for i in range(len(lst)-1):
    new_lst.append((lst[i].strip(),lst[i+1].strip()))
    
new_lst

Out[66]: [('Have', 'free'),
 ('free', 'hours'),
 ('hours', 'and'),
 ('and', 'love'),
 ('love', 'children?'),
 ('children?', 'Drive'),
 ('Drive', 'kids'),
 ('kids', 'to'),
 ('to', 'school,'),
 ('school,', 'soccer'),
 ('soccer', 'practice'),
 ('practice', 'and'),
 ('and', 'other'),
 ('other', 'activities.')]

In [0]:
a = "elle"
b = "leel"

len(a)

In [0]:
# A = 'abcde'
# B = 'cdeab'

# def func(A,B):
#     for i in range(len(A)):
#         if (A[i:] + A[0:i]) == B:
#             return print(f"Equal by shift: {i} and {A[i:] + A[0:i]}" )
#     return print(f"Not Equal by shift" )
            


# func(A,B)

Equal by shift: 2 and cdeab

In [0]:
A = 'abcde'
B = 'cdeab'

# A[-2:] + A[0:-2]
for i in range(len(A)):
    if (A[-i:] + A[0:-i]) == B:
        print("A can shift to form B with " + str(i+1) +" shifts")
        break
    print("not possible with "+ str(i+1)+ " shifts")



# def left_shift(s, n):
#     return s[n:] + s[:n]

# input_str = "abcdef"
# shift_amount = 2
# result = left_shift(input_str, shift_amount)
# print(result)  # Output: "cdefab"

# def right_shift(s, n):
#     return s[-n:] + s[:-n]

# input_str = "abcdef"
# shift_amount = 2
# result = right_shift(input_str, shift_amount)
# print(result)  # Output: "efabcd"

In [0]:
# user_ids = [103, 105, 105, 107, 106, 103, 102, 108, 107, 103, 102]
# tips     = [2, 5, 1, 0, 2, 1, 1, 0, 0, 2, 2]

# tip_dict = {}
# tip_dict = tip_dict.fromkeys(user_ids,0)

# for i in range(len(user_ids)):
#     tip_dict[user_ids[i]] = tip_dict[user_ids[i]] + tips[i]
    

# { k:v for k,v in tip_dict.items() if v == max(tip_dict.values()) }







# user_ids = [103, 105, 105, 107, 106, 103, 102, 108, 107, 103, 102]
# tips = [2, 5, 1, 0, 2, 1, 1, 0, 0, 2, 2]

# tip_dict = {}

# for ind,user in enumerate(user_ids):
#     if user not in tip_dict:
#         tip_dict[user] = tips[ind]
#     else:
#         tip_dict[user] = tip_dict[user] + tips[ind]

# max_tip_user = max(tip_dict, key = tip_dict.get)
# max_tip = tip_dict[max_tip_user]

# print(max_tip_user)
# print(max_tip)











# user_ids = [103, 105, 105, 107, 106, 103, 102, 108, 107, 103, 102]
# tips = [2, 5, 1, 0, 2, 1, 1, 0, 0, 2, 2]

# tip_dict = {}

# def max_tip_user(user_ids,tips):
#     for user,tip in zip(user_ids,tips):
#         if user not in tip_dict:
#             tip_dict[user] = tip
#         else:
#             tip_dict[user] = tip + tip_dict[user]
#     return tip_dict

# final = max_tip_user(user_ids,tips)

# final

In [0]:
# string = 'aaabbbcca' 
# output = '3a3b2c1a'

# current_char = ''
# current_count = 0
# final = ''
# for char in string:
#     if char != current_char:
#         final = final +str(current_count) + current_char 
#         current_char = char
#         current_count = 1
#     elif char == current_char:
#         current_count = current_count + 1
# final = final +str(current_count) + current_char 

# final[1:]





# string = 'aaabbbcca' #---->>> '3a3b2c1a'

# temp = string[0]
# current_char = ''
# final = ''

# for char in string:
#     if char == temp:
#         current_char = current_char + char
#         # print(current_char)
#         temp = char
#         # print(temp)
#     else:
#         final = final + str(len(current_char)) + current_char[0]
#         print(final)
#         temp = char
#         print(temp)
#         current_char = ''
#         current_char = char
#         print(current_char)



# # current_char


# final



string = 'aaabbbcca' 

temp = string[0]
current_char = ''

final =  ''


for char in string:
    if char == temp:
        current_char = current_char + char
        s = str(len(current_char)) + char
        fianl = final + s
        temp = char

In [0]:
# string = 'aaabbbcca' 
# output = '3a3b2c1a'

def func(string):
    c_char  = string[0]
    c_count = 0
    output = ''
    for char in string:
        if char == c_char:
            c_count += 1
        else:
            output += str(c_count) + c_char
            c_char = char
            c_count = 1

    output += str(c_count) + c_char
    return output

output = func('aabaac')
output

Out[43]: '5a1b2a1c'

In [0]:
'final'[-1]

In [30]:
l=[(1,0),(2,3),(4,5)]
z=[e for i in l for e in i]
print(z)

import itertools
z=list(itertools.chain.from_iterable(l))
z

[1, 0, 2, 3, 4, 5]

[1, 0, 2, 3, 4, 5]

In [31]:
l[::-1]

[(4, 5), (2, 3), (1, 0)]

In [34]:
l=[1,2,3]
sum(l)

6

In [35]:
l.index(2)

1

In [45]:
l=[1,2,3,3,4,1,3]
from collections import Counter
c=Counter(l)
mf=c.most_common(1)
mf2=max(c.items(),key=lambda item:item[1])
mf

[(3, 3)]

In [ ]:
def Find_pain(nums,target):
    pair=set()
    s=set()
    for i in nums:
        c=t-i
        if c in s:
            pair.add(tuple(sorted(i,c)))
        seen.add(i)
    return list(pair)

Find_pain()

In [50]:
n=[1,2,3,4,5,3]
def rotation(nums,t): 
        return nums[-t:]+ nums[:-t]

       
rotation(n,3)

[4, 5, 3, 1, 2, 3]

In [53]:
d=[1,2,5,0,3,0,77,0]
d.sort(key=lambda x:x==0)
d

[1, 2, 5, 3, 77, 0, 0, 0]

In [56]:
list1 = ['A', 'B']
list2 = [1, 2, 3]
p=[(x,y) for x in list1 for y in list2]
p

[('A', 1), ('A', 2), ('A', 3), ('B', 1), ('B', 2), ('B', 3)]

In [58]:
dict_a = {'name': 'Alice', 'age': 25}
dict_b = {'job': 'Engineer', 'age': 26}

me= dict_a | dict_b
me

{'name': 'Alice', 'age': 26, 'job': 'Engineer'}

In [64]:
h='hello python'
' '.join(h.split()[::-1])

'python hello'

In [75]:
s = {'Alice': 50, 'Bob': 75, 'Charlie': 40}
from collections import Counter
h= max(s.items(),key=lambda item:item[1])
u=sorted(s.items(),key=lambda item:item[1],reverse=True)
u

[('Bob', 75), ('Alice', 50), ('Charlie', 40)]

In [79]:
s = {'Alice': 50, 'Bob': 75, 'Charlie': 40}
inr={v:k for k, v in s.items()}
inr

{50: 'Alice', 75: 'Bob', 40: 'Charlie'}

In [85]:
j='ankita'

def fq(s):
    c=Counter(s)
    for i in s:
        if c[i]== 1:
            return i
    return None

fq(j)

'n'

In [86]:

def longest_common_prefix(words):
    if not words: return ""
    prefix = words[0]
    for word in words[1:]:
        while not word.startswith(prefix):
            prefix = prefix[:-1]
            if not prefix:
                return ""
    return prefix

print(longest_common_prefix(["flower", "flow", "flight"]))  # Output: "fl"

fl

In [ ]:
def run_length_encoding(s): aayyym
    if not s: return ""
    encoded, count = [], 1
    for i in range(1, len(s)):   1-6
        if s[i] == s[i - 1]:
            count += 1
        else:
            encoded.append(s[i - 1] + str(count))
            count = 1
    encoded.append(s[-1] + str(count))
    return "".join(encoded)

print(run_length_encoding(""))

In [108]:
#  Find the Most Frequent Word in a String
def most_frequent_word(s):
    words = s.split()
    return max(Counter(words), key=Counter(words).get)

print( most_frequent_word("apple banana apple orange banana apple") )

apple

In [116]:
s="apple banana apple orange banana apple"
o=s.split()
n=max(Counter(o),key=Counter(o).get)
m=Counter(o).most_common(1)
m
n

'apple'

In [ ]:
def all_palindromes(s):
    results = []
    for i in range(len(s)):
        for l, r in [(i, i), (i, i + 1)]:
            while l >= 0 and r < len(s) and s[l] == s[r]:
                results.append(s[l:r+1])
                l -= 1
                r += 1
    return results

all_palindromes("babad")

['b', 'a', 'bab', 'b', 'aba', 'a', 'd']

In [ ]:
#  Find the Longest Palindromic Substring
def longest_palindrome(s):
    def expand_around_center(left, right):
        while left >= 0 and right < len(s) and s[left] == s[right]:
            left -= 1
            right += 1
        return s[left+1:right]
    
    result = ""
    for i in range(len(s)):
        for temp in (expand_around_center(i, i), expand_around_center(i, i+1)):
            if len(temp) > len(result):
                result = temp
    return result

print(longest_palindrome("babad"))  # Output: "bab" or "aba"

In [121]:
# Merge

def merge_sort(arr):
    if len(arr) <= 1:
        return arr
    mid = len(arr) // 2
    left = merge_sort(arr[:mid])
    right = merge_sort(arr[mid:])
    return merge(left, right)

def merge(left, right):
    sorted_arr = []
    i = j = 0
    while i < len(left) and j < len(right):
        if left[i] < right[j]:
            sorted_arr.append(left[i])
            i += 1
        else:
            sorted_arr.append(right[j])
            j += 1
    sorted_arr.extend(left[i:])
    sorted_arr.extend(right[j:])
    return sorted_arr

print(merge_sort([5, 3, 8, 1, 2]))

[1, 2, 3, 5, 8]

In [122]:
# Find all palindromic substrings in a given string (length > 2)
s = "nana"

def func(s):
    lst =[]
    for i in range(len(s)):
        for j in range(i, len(s)):
            if s[i:j+1] == s[i:j+1][::-1] and len(s[i:j+1]) > 2:
                lst.append(s[i:j+1]) 
    return lst
            

func(s)

['nan', 'ana']

In [123]:

# Check if a given string is a palindrome, ignoring spaces, punctuation, and case sensitivity.

s = "A man, a plan, a canal, Panama!a"

def func(s):
    string =  s.replace(',', '').replace(' ', '').replace('!', '').lower()
    if string == string[::-1]:
        print(" Planlindrome string" )
    else:
        print(" Not Plamlindrome string" )
func(s)

 Not Plamlindrome string

In [125]:
from collections import Counter
def func(s1,s2):
    if len(s1)!=len(s2):
        return print("Not Anagram")
    d1,d2 = Counter(s1), Counter(s2)
    if d1==d2:
        return print("ANAGRAM"),print(d1),print(d2)
    else:
        print("Not Anagram")
    
func('Anki','anki')

Not Anagram